name: Build and Push Alloy Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.2.3)"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  release-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      ECR_REGISTRY: 883233562864.dkr.ecr.eu-central-1.amazonaws.com
      ECR_REPOSITORY: grafana-cloud-alloy

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::883233562864:role/gha-ecr-pusher
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push alloy Image
        env:
          IMAGE_URI: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ inputs.version }}
        run: |
          docker build -t "$IMAGE_URI" ./alloy
          docker push "$IMAGE_URI"
